name: cme
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.7+41

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  # file_picker: ^2.1.0
  # gx_file_picker: ^1.9.0+2


  step_progress_indicator: ^1.0.2
  pin_code_text_field: ^1.8.0
  flutter_swiper_null_safety: ^1.0.2
  flutter_icons_null_safety: ^1.1.0
  flutter_slidable: ^1.3.0
  percent_indicator: ^4.2.1
  intl: ^0.17.0
 # super_tooltip: ^1.0.1
  smooth_star_rating_nsafe: ^1.0.0+1
  sliding_up_panel: ^2.0.0+1

  #location: ^4.4.0
  google_maps_flutter: ^2.1.8
  geolocator: ^8.2.1
  geocoding: ^2.0.4
  #geodesy: ^0.3.2
  overlay_tooltip: ^0.2.1

  address_search_field: ^5.0.3
  #syncfusion_flutter_charts: ^20.1.61
  menu_button: ^1.4.2+1
  dotted_border: ^2.0.0+2
 # some_calendar: ^1.2.6
  jiffy: ^5.0.0
  simple_tooltip: ^1.0.0
  permission_handler: ^10.0.0
  sleek_circular_slider: ^2.0.1

 # draw_graph: ^0.0.1
 # graph_widget: ^1.0.14

  location_permissions: ^4.0.1

 # bubble_chart: ^0.4.0

#  cloud_firestore: "^3.1.18"
#  firebase_auth: ^3.3.20
#  firebase_core: ^1.18.0
#  firebase_messaging: ^11.4.2

#  firebase_auth: ^3.6.1
#  firebase_core: ^1.20.0
#  firebase_messaging: ^13.0.4

  cloud_firestore: 4.4.4
  firebase_auth: 4.1.0
  firebase_core: 2.7.1
  firebase_messaging: 14.0.3

  scoped_model: ^2.0.0-nullsafety.0

  dio: ^4.0.6
  http: ^0.13.4

  image_picker: ^0.8.5+3
  image_cropper: ^2.0.3

  flutter_markdown: ^0.6.10

  # flutter_datetime_picker: ^1.4.0
  flutter_datetime_picker:
    git:
      url: https://github.com/espresso3389/flutter_datetime_picker

  credit_card_type_detector: ^2.0.0
  #credit_card_field: ^1.0.2

  #intl_phone_number_input: ^0.7.0+2
  flutter_countdown_timer: ^4.1.0
  local_auth: ^2.1.0


  shared_preferences: ^2.0.17
  stop_watch_timer: ^1.5.0

  url_launcher: ^6.1.4
  #after_layout: ^1.1.1+1
  #path_provider: ^2.0.11
  flutter_calendar_carousel: ^2.4.1
  contacts_service: ^0.6.3
  flutter_stripe: ^6.0.0

  progress_dialog_null_safe: ^1.0.7

  device_calendar: ^4.2.0
  flutter_echarts: ^2.4.0

  agora_rtc_engine: ^6.1.1+1
  uuid: ^3.0.7

  flutter_typeahead: ^4.3.7
  # flutter_social_content_share: ^0.0.3
  share_plus: ^4.0.10
  purchases_flutter: ^3.8.0

  fl_chart: ^0.55.0

  #charts_flutter: ^0.12.0
  community_charts_flutter: ^1.0.1
  rflutter_alert: ^2.0.4
 # social_share: ^2.2.1
  fluttertoast: ^8.0.9

  #flutter_gauge: ^1.0.8
  #flutter_scale: ^0.1.2

  provider: ^6.0.3
  intl_phone_field: ^3.1.0
  file_picker: ^4.6.1
  email_validator: ^2.1.17
  widgets_to_image: ^0.0.2
  path_provider: ^2.0.12
  keyboard_dismisser: ^3.0.0
  image_watermark: ^0.0.5
  get: ^4.6.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  dependency_validator: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/
    - assets/
    - images/avtar/

  fonts:
    - family: R-Flex
      fonts:
        - asset: fonts/RFlexBold-VGzLZ.ttf
          weight: 700
        - asset: fonts/R-FLEX-MEDIUM.otf
          weight: 500
        - asset: fonts/RFlexRegular-JRJ8j.ttf
          weight: 100
    - family: ROBOTO
      fonts:
        - asset: fonts/Roboto-Bold.ttf